/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'UartSendMsg'
 * message type.
 */

public class UartSendMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 13;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 123;

    /** Create a new UartSendMsg of size 13. */
    public UartSendMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new UartSendMsg of the given data_length. */
    public UartSendMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UartSendMsg with the given data_length
     * and base offset.
     */
    public UartSendMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UartSendMsg using the given byte array
     * as backing store.
     */
    public UartSendMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UartSendMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public UartSendMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UartSendMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public UartSendMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UartSendMsg embedded in the given message
     * at the given base offset.
     */
    public UartSendMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UartSendMsg embedded in the given message
     * at the given base offset and length.
     */
    public UartSendMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <UartSendMsg> \n";
      try {
        s += "  [cmd_type=0x"+Long.toHexString(get_cmd_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sample=0x"+Long.toHexString(get_sample())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [source=0x"+Long.toHexString(get_source())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pkt_num=0x"+Long.toHexString(get_pkt_num())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [serial=0x"+Long.toHexString(get_serial())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [age=0x"+Long.toHexString(get_age())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmd_type
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmd_type' is signed (false).
     */
    public static boolean isSigned_cmd_type() {
        return false;
    }

    /**
     * Return whether the field 'cmd_type' is an array (false).
     */
    public static boolean isArray_cmd_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cmd_type'
     */
    public static int offset_cmd_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmd_type'
     */
    public static int offsetBits_cmd_type() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'cmd_type'
     */
    public short get_cmd_type() {
        return (short)getUIntBEElement(offsetBits_cmd_type(), 8);
    }

    /**
     * Set the value of the field 'cmd_type'
     */
    public void set_cmd_type(short value) {
        setUIntBEElement(offsetBits_cmd_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cmd_type'
     */
    public static int size_cmd_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cmd_type'
     */
    public static int sizeBits_cmd_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sample
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sample' is signed (false).
     */
    public static boolean isSigned_sample() {
        return false;
    }

    /**
     * Return whether the field 'sample' is an array (false).
     */
    public static boolean isArray_sample() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sample'
     */
    public static int offset_sample() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sample'
     */
    public static int offsetBits_sample() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'sample'
     */
    public int get_sample() {
        return (int)getUIntBEElement(offsetBits_sample(), 16);
    }

    /**
     * Set the value of the field 'sample'
     */
    public void set_sample(int value) {
        setUIntBEElement(offsetBits_sample(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sample'
     */
    public static int size_sample() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sample'
     */
    public static int sizeBits_sample() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: source
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'source' is signed (false).
     */
    public static boolean isSigned_source() {
        return false;
    }

    /**
     * Return whether the field 'source' is an array (false).
     */
    public static boolean isArray_source() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'source'
     */
    public static int offset_source() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'source'
     */
    public static int offsetBits_source() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'source'
     */
    public int get_source() {
        return (int)getUIntBEElement(offsetBits_source(), 16);
    }

    /**
     * Set the value of the field 'source'
     */
    public void set_source(int value) {
        setUIntBEElement(offsetBits_source(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'source'
     */
    public static int size_source() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'source'
     */
    public static int sizeBits_source() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pkt_num
    //   Field type: int, unsigned
    //   Offset (bits): 40
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pkt_num' is signed (false).
     */
    public static boolean isSigned_pkt_num() {
        return false;
    }

    /**
     * Return whether the field 'pkt_num' is an array (false).
     */
    public static boolean isArray_pkt_num() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pkt_num'
     */
    public static int offset_pkt_num() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pkt_num'
     */
    public static int offsetBits_pkt_num() {
        return 40;
    }

    /**
     * Return the value (as a int) of the field 'pkt_num'
     */
    public int get_pkt_num() {
        return (int)getUIntBEElement(offsetBits_pkt_num(), 16);
    }

    /**
     * Set the value of the field 'pkt_num'
     */
    public void set_pkt_num(int value) {
        setUIntBEElement(offsetBits_pkt_num(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pkt_num'
     */
    public static int size_pkt_num() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pkt_num'
     */
    public static int sizeBits_pkt_num() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: serial
    //   Field type: int, unsigned
    //   Offset (bits): 56
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'serial' is signed (false).
     */
    public static boolean isSigned_serial() {
        return false;
    }

    /**
     * Return whether the field 'serial' is an array (false).
     */
    public static boolean isArray_serial() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'serial'
     */
    public static int offset_serial() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'serial'
     */
    public static int offsetBits_serial() {
        return 56;
    }

    /**
     * Return the value (as a int) of the field 'serial'
     */
    public int get_serial() {
        return (int)getUIntBEElement(offsetBits_serial(), 16);
    }

    /**
     * Set the value of the field 'serial'
     */
    public void set_serial(int value) {
        setUIntBEElement(offsetBits_serial(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'serial'
     */
    public static int size_serial() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'serial'
     */
    public static int sizeBits_serial() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: age
    //   Field type: long, unsigned
    //   Offset (bits): 72
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'age' is signed (false).
     */
    public static boolean isSigned_age() {
        return false;
    }

    /**
     * Return whether the field 'age' is an array (false).
     */
    public static boolean isArray_age() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'age'
     */
    public static int offset_age() {
        return (72 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'age'
     */
    public static int offsetBits_age() {
        return 72;
    }

    /**
     * Return the value (as a long) of the field 'age'
     */
    public long get_age() {
        return (long)getUIntBEElement(offsetBits_age(), 32);
    }

    /**
     * Set the value of the field 'age'
     */
    public void set_age(long value) {
        setUIntBEElement(offsetBits_age(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'age'
     */
    public static int size_age() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'age'
     */
    public static int sizeBits_age() {
        return 32;
    }

}
