/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'CmdMsg'
 * message type.
 */

public class CmdMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 9;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 124;

    /** Create a new CmdMsg of size 9. */
    public CmdMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new CmdMsg of the given data_length. */
    public CmdMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg with the given data_length
     * and base offset.
     */
    public CmdMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg using the given byte array
     * as backing store.
     */
    public CmdMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public CmdMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public CmdMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg embedded in the given message
     * at the given base offset.
     */
    public CmdMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CmdMsg embedded in the given message
     * at the given base offset and length.
     */
    public CmdMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <CmdMsg> \n";
      try {
        s += "  [cmd_type=0x"+Long.toHexString(get_cmd_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [ref_time_m=0x"+Long.toHexString(get_ref_time_m())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [ref_time_l=0x"+Long.toHexString(get_ref_time_l())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmd_type
    //   Field type: short, signed
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmd_type' is signed (true).
     */
    public static boolean isSigned_cmd_type() {
        return true;
    }

    /**
     * Return whether the field 'cmd_type' is an array (false).
     */
    public static boolean isArray_cmd_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cmd_type'
     */
    public static int offset_cmd_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmd_type'
     */
    public static int offsetBits_cmd_type() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'cmd_type'
     */
    public short get_cmd_type() {
        return (short)getUIntBEElement(offsetBits_cmd_type(), 8);
    }

    /**
     * Set the value of the field 'cmd_type'
     */
    public void set_cmd_type(short value) {
        setUIntBEElement(offsetBits_cmd_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cmd_type'
     */
    public static int size_cmd_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cmd_type'
     */
    public static int sizeBits_cmd_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: ref_time_m
    //   Field type: int, signed
    //   Offset (bits): 8
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'ref_time_m' is signed (true).
     */
    public static boolean isSigned_ref_time_m() {
        return true;
    }

    /**
     * Return whether the field 'ref_time_m' is an array (false).
     */
    public static boolean isArray_ref_time_m() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'ref_time_m'
     */
    public static int offset_ref_time_m() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'ref_time_m'
     */
    public static int offsetBits_ref_time_m() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'ref_time_m'
     */
    public int get_ref_time_m() {
        return (int)getSIntBEElement(offsetBits_ref_time_m(), 32);
    }

    /**
     * Set the value of the field 'ref_time_m'
     */
    public void set_ref_time_m(int value) {
        setSIntBEElement(offsetBits_ref_time_m(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'ref_time_m'
     */
    public static int size_ref_time_m() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'ref_time_m'
     */
    public static int sizeBits_ref_time_m() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: ref_time_l
    //   Field type: int, signed
    //   Offset (bits): 40
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'ref_time_l' is signed (true).
     */
    public static boolean isSigned_ref_time_l() {
        return true;
    }

    /**
     * Return whether the field 'ref_time_l' is an array (false).
     */
    public static boolean isArray_ref_time_l() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'ref_time_l'
     */
    public static int offset_ref_time_l() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'ref_time_l'
     */
    public static int offsetBits_ref_time_l() {
        return 40;
    }

    /**
     * Return the value (as a int) of the field 'ref_time_l'
     */
    public int get_ref_time_l() {
        return (int)getSIntBEElement(offsetBits_ref_time_l(), 32);
    }

    /**
     * Set the value of the field 'ref_time_l'
     */
    public void set_ref_time_l(int value) {
        setSIntBEElement(offsetBits_ref_time_l(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'ref_time_l'
     */
    public static int size_ref_time_l() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'ref_time_l'
     */
    public static int sizeBits_ref_time_l() {
        return 32;
    }

}
