/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ChannelMsg'
 * message type.
 */

public class ChannelMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 11;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 121;

    /** Create a new ChannelMsg of size 11. */
    public ChannelMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ChannelMsg of the given data_length. */
    public ChannelMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChannelMsg with the given data_length
     * and base offset.
     */
    public ChannelMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChannelMsg using the given byte array
     * as backing store.
     */
    public ChannelMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChannelMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ChannelMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChannelMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ChannelMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChannelMsg embedded in the given message
     * at the given base offset.
     */
    public ChannelMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChannelMsg embedded in the given message
     * at the given base offset and length.
     */
    public ChannelMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ChannelMsg> \n";
      try {
        s += "  [source=0x"+Long.toHexString(get_source())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [neigh_ID=0x"+Long.toHexString(get_neigh_ID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pkt_ID=0x"+Long.toHexString(get_pkt_ID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [num_pkts=0x"+Long.toHexString(get_num_pkts())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [lqi=0x"+Long.toHexString(get_lqi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [channel_ID=0x"+Long.toHexString(get_channel_ID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pot=0x"+Long.toHexString(get_pot())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [len=0x"+Long.toHexString(get_len())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: source
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'source' is signed (false).
     */
    public static boolean isSigned_source() {
        return false;
    }

    /**
     * Return whether the field 'source' is an array (false).
     */
    public static boolean isArray_source() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'source'
     */
    public static int offset_source() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'source'
     */
    public static int offsetBits_source() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'source'
     */
    public int get_source() {
        return (int)getUIntBEElement(offsetBits_source(), 16);
    }

    /**
     * Set the value of the field 'source'
     */
    public void set_source(int value) {
        setUIntBEElement(offsetBits_source(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'source'
     */
    public static int size_source() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'source'
     */
    public static int sizeBits_source() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: neigh_ID
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'neigh_ID' is signed (false).
     */
    public static boolean isSigned_neigh_ID() {
        return false;
    }

    /**
     * Return whether the field 'neigh_ID' is an array (false).
     */
    public static boolean isArray_neigh_ID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'neigh_ID'
     */
    public static int offset_neigh_ID() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'neigh_ID'
     */
    public static int offsetBits_neigh_ID() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'neigh_ID'
     */
    public int get_neigh_ID() {
        return (int)getUIntBEElement(offsetBits_neigh_ID(), 16);
    }

    /**
     * Set the value of the field 'neigh_ID'
     */
    public void set_neigh_ID(int value) {
        setUIntBEElement(offsetBits_neigh_ID(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'neigh_ID'
     */
    public static int size_neigh_ID() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'neigh_ID'
     */
    public static int sizeBits_neigh_ID() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pkt_ID
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pkt_ID' is signed (false).
     */
    public static boolean isSigned_pkt_ID() {
        return false;
    }

    /**
     * Return whether the field 'pkt_ID' is an array (false).
     */
    public static boolean isArray_pkt_ID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pkt_ID'
     */
    public static int offset_pkt_ID() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pkt_ID'
     */
    public static int offsetBits_pkt_ID() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'pkt_ID'
     */
    public short get_pkt_ID() {
        return (short)getUIntBEElement(offsetBits_pkt_ID(), 8);
    }

    /**
     * Set the value of the field 'pkt_ID'
     */
    public void set_pkt_ID(short value) {
        setUIntBEElement(offsetBits_pkt_ID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'pkt_ID'
     */
    public static int size_pkt_ID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pkt_ID'
     */
    public static int sizeBits_pkt_ID() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: num_pkts
    //   Field type: short, unsigned
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'num_pkts' is signed (false).
     */
    public static boolean isSigned_num_pkts() {
        return false;
    }

    /**
     * Return whether the field 'num_pkts' is an array (false).
     */
    public static boolean isArray_num_pkts() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'num_pkts'
     */
    public static int offset_num_pkts() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'num_pkts'
     */
    public static int offsetBits_num_pkts() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'num_pkts'
     */
    public short get_num_pkts() {
        return (short)getUIntBEElement(offsetBits_num_pkts(), 8);
    }

    /**
     * Set the value of the field 'num_pkts'
     */
    public void set_num_pkts(short value) {
        setUIntBEElement(offsetBits_num_pkts(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'num_pkts'
     */
    public static int size_num_pkts() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'num_pkts'
     */
    public static int sizeBits_num_pkts() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short, unsigned
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'rssi'
     */
    public short get_rssi() {
        return (short)getUIntBEElement(offsetBits_rssi(), 8);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(short value) {
        setUIntBEElement(offsetBits_rssi(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: lqi
    //   Field type: short, unsigned
    //   Offset (bits): 56
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'lqi' is signed (false).
     */
    public static boolean isSigned_lqi() {
        return false;
    }

    /**
     * Return whether the field 'lqi' is an array (false).
     */
    public static boolean isArray_lqi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'lqi'
     */
    public static int offset_lqi() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'lqi'
     */
    public static int offsetBits_lqi() {
        return 56;
    }

    /**
     * Return the value (as a short) of the field 'lqi'
     */
    public short get_lqi() {
        return (short)getUIntBEElement(offsetBits_lqi(), 8);
    }

    /**
     * Set the value of the field 'lqi'
     */
    public void set_lqi(short value) {
        setUIntBEElement(offsetBits_lqi(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'lqi'
     */
    public static int size_lqi() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'lqi'
     */
    public static int sizeBits_lqi() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: channel_ID
    //   Field type: short, unsigned
    //   Offset (bits): 64
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'channel_ID' is signed (false).
     */
    public static boolean isSigned_channel_ID() {
        return false;
    }

    /**
     * Return whether the field 'channel_ID' is an array (false).
     */
    public static boolean isArray_channel_ID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'channel_ID'
     */
    public static int offset_channel_ID() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'channel_ID'
     */
    public static int offsetBits_channel_ID() {
        return 64;
    }

    /**
     * Return the value (as a short) of the field 'channel_ID'
     */
    public short get_channel_ID() {
        return (short)getUIntBEElement(offsetBits_channel_ID(), 8);
    }

    /**
     * Set the value of the field 'channel_ID'
     */
    public void set_channel_ID(short value) {
        setUIntBEElement(offsetBits_channel_ID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'channel_ID'
     */
    public static int size_channel_ID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'channel_ID'
     */
    public static int sizeBits_channel_ID() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pot
    //   Field type: short, unsigned
    //   Offset (bits): 72
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pot' is signed (false).
     */
    public static boolean isSigned_pot() {
        return false;
    }

    /**
     * Return whether the field 'pot' is an array (false).
     */
    public static boolean isArray_pot() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pot'
     */
    public static int offset_pot() {
        return (72 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pot'
     */
    public static int offsetBits_pot() {
        return 72;
    }

    /**
     * Return the value (as a short) of the field 'pot'
     */
    public short get_pot() {
        return (short)getUIntBEElement(offsetBits_pot(), 8);
    }

    /**
     * Set the value of the field 'pot'
     */
    public void set_pot(short value) {
        setUIntBEElement(offsetBits_pot(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'pot'
     */
    public static int size_pot() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pot'
     */
    public static int sizeBits_pot() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: len
    //   Field type: short, unsigned
    //   Offset (bits): 80
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'len' is signed (false).
     */
    public static boolean isSigned_len() {
        return false;
    }

    /**
     * Return whether the field 'len' is an array (false).
     */
    public static boolean isArray_len() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'len'
     */
    public static int offset_len() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'len'
     */
    public static int offsetBits_len() {
        return 80;
    }

    /**
     * Return the value (as a short) of the field 'len'
     */
    public short get_len() {
        return (short)getUIntBEElement(offsetBits_len(), 8);
    }

    /**
     * Set the value of the field 'len'
     */
    public void set_len(short value) {
        setUIntBEElement(offsetBits_len(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'len'
     */
    public static int size_len() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'len'
     */
    public static int sizeBits_len() {
        return 8;
    }

}
