#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'TestMsg'
# message type.
#

import tos
import sys

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 2

# The Active Message type associated with this message.
AM_TYPE = 137

class TestMsg(tos.packet):

	def __init__(self, packet = None):
		tos.Packet.__init__(self, [('counter', 'int', 2)], packet)


