/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'HeaderMsg'
 * message type.
 */

public class HeaderMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 3;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 2;

    /** Create a new HeaderMsg of size 3. */
    public HeaderMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new HeaderMsg of the given data_length. */
    public HeaderMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HeaderMsg with the given data_length
     * and base offset.
     */
    public HeaderMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HeaderMsg using the given byte array
     * as backing store.
     */
    public HeaderMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HeaderMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public HeaderMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HeaderMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public HeaderMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HeaderMsg embedded in the given message
     * at the given base offset.
     */
    public HeaderMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HeaderMsg embedded in the given message
     * at the given base offset and length.
     */
    public HeaderMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <HeaderMsg> \n";
      try {
        s += "  [ack.force_awake=0x"+Long.toHexString(get_ack_force_awake())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [ack.node_id=0x"+Long.toHexString(get_ack_node_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [header.type=0x"+Long.toHexString(get_header_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [header.unique_id=0x"+Long.toHexString(get_header_unique_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: ack.force_awake
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'ack.force_awake' is signed (false).
     */
    public static boolean isSigned_ack_force_awake() {
        return false;
    }

    /**
     * Return whether the field 'ack.force_awake' is an array (false).
     */
    public static boolean isArray_ack_force_awake() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'ack.force_awake'
     */
    public static int offset_ack_force_awake() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'ack.force_awake'
     */
    public static int offsetBits_ack_force_awake() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'ack.force_awake'
     */
    public short get_ack_force_awake() {
        return (short)getUIntBEElement(offsetBits_ack_force_awake(), 8);
    }

    /**
     * Set the value of the field 'ack.force_awake'
     */
    public void set_ack_force_awake(short value) {
        setUIntBEElement(offsetBits_ack_force_awake(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'ack.force_awake'
     */
    public static int size_ack_force_awake() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'ack.force_awake'
     */
    public static int sizeBits_ack_force_awake() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: ack.node_id
    //   Field type: int
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'ack.node_id' is signed (false).
     */
    public static boolean isSigned_ack_node_id() {
        return false;
    }

    /**
     * Return whether the field 'ack.node_id' is an array (false).
     */
    public static boolean isArray_ack_node_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'ack.node_id'
     */
    public static int offset_ack_node_id() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'ack.node_id'
     */
    public static int offsetBits_ack_node_id() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'ack.node_id'
     */
    public int get_ack_node_id() {
        return (int)getUIntBEElement(offsetBits_ack_node_id(), 16);
    }

    /**
     * Set the value of the field 'ack.node_id'
     */
    public void set_ack_node_id(int value) {
        setUIntBEElement(offsetBits_ack_node_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'ack.node_id'
     */
    public static int size_ack_node_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'ack.node_id'
     */
    public static int sizeBits_ack_node_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: header.type
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'header.type' is signed (false).
     */
    public static boolean isSigned_header_type() {
        return false;
    }

    /**
     * Return whether the field 'header.type' is an array (false).
     */
    public static boolean isArray_header_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'header.type'
     */
    public static int offset_header_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'header.type'
     */
    public static int offsetBits_header_type() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'header.type'
     */
    public short get_header_type() {
        return (short)getUIntBEElement(offsetBits_header_type(), 8);
    }

    /**
     * Set the value of the field 'header.type'
     */
    public void set_header_type(short value) {
        setUIntBEElement(offsetBits_header_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'header.type'
     */
    public static int size_header_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'header.type'
     */
    public static int sizeBits_header_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: header.unique_id
    //   Field type: int
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'header.unique_id' is signed (false).
     */
    public static boolean isSigned_header_unique_id() {
        return false;
    }

    /**
     * Return whether the field 'header.unique_id' is an array (false).
     */
    public static boolean isArray_header_unique_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'header.unique_id'
     */
    public static int offset_header_unique_id() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'header.unique_id'
     */
    public static int offsetBits_header_unique_id() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'header.unique_id'
     */
    public int get_header_unique_id() {
        return (int)getUIntBEElement(offsetBits_header_unique_id(), 16);
    }

    /**
     * Set the value of the field 'header.unique_id'
     */
    public void set_header_unique_id(int value) {
        setUIntBEElement(offsetBits_header_unique_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'header.unique_id'
     */
    public static int size_header_unique_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'header.unique_id'
     */
    public static int sizeBits_header_unique_id() {
        return 16;
    }

}
