/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RecvMsg'
 * message type.
 */

public class RecvMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 0;

    /** Create a new RecvMsg of size 10. */
    public RecvMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RecvMsg of the given data_length. */
    public RecvMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RecvMsg with the given data_length
     * and base offset.
     */
    public RecvMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RecvMsg using the given byte array
     * as backing store.
     */
    public RecvMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RecvMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RecvMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RecvMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RecvMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RecvMsg embedded in the given message
     * at the given base offset.
     */
    public RecvMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RecvMsg embedded in the given message
     * at the given base offset and length.
     */
    public RecvMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RecvMsg> \n";
      try {
        s += "  [sample=0x"+Long.toHexString(get_sample())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [pkt_num=0x"+Long.toHexString(get_pkt_num())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [serial=0x"+Long.toHexString(get_serial())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [age=0x"+Long.toHexString(get_age())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sample
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sample' is signed (false).
     */
    public static boolean isSigned_sample() {
        return false;
    }

    /**
     * Return whether the field 'sample' is an array (false).
     */
    public static boolean isArray_sample() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sample'
     */
    public static int offset_sample() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sample'
     */
    public static int offsetBits_sample() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'sample'
     */
    public int get_sample() {
        return (int)getUIntBEElement(offsetBits_sample(), 16);
    }

    /**
     * Set the value of the field 'sample'
     */
    public void set_sample(int value) {
        setUIntBEElement(offsetBits_sample(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sample'
     */
    public static int size_sample() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sample'
     */
    public static int sizeBits_sample() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: pkt_num
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'pkt_num' is signed (false).
     */
    public static boolean isSigned_pkt_num() {
        return false;
    }

    /**
     * Return whether the field 'pkt_num' is an array (false).
     */
    public static boolean isArray_pkt_num() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'pkt_num'
     */
    public static int offset_pkt_num() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'pkt_num'
     */
    public static int offsetBits_pkt_num() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'pkt_num'
     */
    public int get_pkt_num() {
        return (int)getUIntBEElement(offsetBits_pkt_num(), 16);
    }

    /**
     * Set the value of the field 'pkt_num'
     */
    public void set_pkt_num(int value) {
        setUIntBEElement(offsetBits_pkt_num(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'pkt_num'
     */
    public static int size_pkt_num() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'pkt_num'
     */
    public static int sizeBits_pkt_num() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: serial
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'serial' is signed (false).
     */
    public static boolean isSigned_serial() {
        return false;
    }

    /**
     * Return whether the field 'serial' is an array (false).
     */
    public static boolean isArray_serial() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'serial'
     */
    public static int offset_serial() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'serial'
     */
    public static int offsetBits_serial() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'serial'
     */
    public int get_serial() {
        return (int)getUIntBEElement(offsetBits_serial(), 16);
    }

    /**
     * Set the value of the field 'serial'
     */
    public void set_serial(int value) {
        setUIntBEElement(offsetBits_serial(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'serial'
     */
    public static int size_serial() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'serial'
     */
    public static int sizeBits_serial() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: age
    //   Field type: long, unsigned
    //   Offset (bits): 48
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'age' is signed (false).
     */
    public static boolean isSigned_age() {
        return false;
    }

    /**
     * Return whether the field 'age' is an array (false).
     */
    public static boolean isArray_age() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'age'
     */
    public static int offset_age() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'age'
     */
    public static int offsetBits_age() {
        return 48;
    }

    /**
     * Return the value (as a long) of the field 'age'
     */
    public long get_age() {
        return (long)getUIntBEElement(offsetBits_age(), 32);
    }

    /**
     * Set the value of the field 'age'
     */
    public void set_age(long value) {
        setUIntBEElement(offsetBits_age(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'age'
     */
    public static int size_age() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'age'
     */
    public static int sizeBits_age() {
        return 32;
    }

}
